"""python3 tools/sprites_ts.py: writes plugin/hooks/sprites.ts and bashou.ts from the sprites in plugin/pets/.

The mod reads no file but Bashou's save (see tools/capabilities.json), so the sprites travel inside its code. A test checks the generated file matches the JSON, so edit the JSON and rerun this.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PETS = ROOT / "plugin/pets"
OUT = ROOT / "plugin/hooks/sprites.ts"
BASHOU_OUT = ROOT / "plugin/hooks/bashou.ts"


def camel(name):
    return re.sub(r"_(\w)", lambda m: m.group(1).upper(), name)                 # pea_crab -> peaCrab


def source():
    lines = ["// Generated by tools/sprites_ts.py from plugin/pets/*.json: edit the JSON, then rerun it.",
             "import type { Sprite } from './sprite'", "",
             "// Claudou's crabs (camelCase ids), then Bashou's pets (snake_case ids, from bashou.json).",
             "export const SPRITES: Record<string, Sprite> = {"]
    for path in sorted(PETS.glob("*.json")):
        if path.name == "bashou.json":
            continue
        d = json.loads(path.read_text())
        sprite = {"palette": d["palette"], "base": d["base"], "poses": d["poses"]}
        lines.append(f"  {camel(path.stem)}: {json.dumps(sprite, ensure_ascii=False)},")
    for pet_id, d in json.loads((PETS / "bashou.json").read_text())["pets"].items():
        sprite = {"palette": d["palette"], "base": d["base"], "poses": d["poses"]}
        lines.append(f"  {pet_id}: {json.dumps(sprite, ensure_ascii=False)},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def bashou_source():
    d = json.loads((PETS / "bashou.json").read_text())
    names = {pet_id: pet["name"] for pet_id, pet in d["pets"].items()}
    return "\n".join([
        "// Generated by tools/sprites_ts.py from plugin/pets/bashou.json (tools/import_bashou.py): rerun them.",
        "import type { Language } from './messages'", "",
        "export type Family = { forms: string[]; starter: boolean; blurb: Record<Language, string> }", "",
        "// Every Bashou pet's name, in every language.",
        f"export const BASHOU_NAMES: Record<string, Record<Language, string>> = {json.dumps(names, ensure_ascii=False)}", "",
        "// Bashou's families: their forms in order, and whether it is a starter line.",
        f"export const BASHOU_FAMILIES: Record<string, Family> = {json.dumps(d['families'], ensure_ascii=False)}", ""])


if __name__ == "__main__":
    if sys.argv[1:] == ["--check"]:
        fresh = OUT.read_text() == source() and BASHOU_OUT.read_text() == bashou_source()
        sys.exit(0 if fresh else "plugin/hooks/sprites.ts or bashou.ts is out of date: run tools/sprites_ts.py")
    OUT.write_text(source())
    BASHOU_OUT.write_text(bashou_source())
