"""python3 tools/sprites_ts.py: writes plugin/hooks/sprites.ts from the sprites in plugin/pets/.

The mod can't read files (it has no filesystem access, on purpose: see tools/capabilities.json), so the sprites
travel inside its code. A test checks the generated file matches the JSON, so edit the JSON and rerun this.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PETS = ROOT / "plugin/pets"
OUT = ROOT / "plugin/hooks/sprites.ts"


def camel(name):
    return re.sub(r"_(\w)", lambda m: m.group(1).upper(), name)                 # pea_crab -> peaCrab


def source():
    lines = ["// Generated by tools/sprites_ts.py from plugin/pets/*.json: edit the JSON, then rerun it.",
             "import type { Form } from './growth'", "import type { Sprite } from './sprite'", "", "// Every form has its sprite: the type makes sure of it.", "export const SPRITES: Record<Form, Sprite> = {"]
    for path in sorted(PETS.glob("*.json")):
        d = json.loads(path.read_text())
        sprite = {"palette": d["palette"], "base": d["base"], "poses": d["poses"]}
        lines.append(f"  {camel(path.stem)}: {json.dumps(sprite, ensure_ascii=False)},")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if sys.argv[1:] == ["--check"]:
        sys.exit(0 if OUT.read_text() == source() else "plugin/hooks/sprites.ts is out of date: run tools/sprites_ts.py")
    OUT.write_text(source())
